services:
  playwright:

    build:
      context: .
      dockerfile: Dockerfile.playwright
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    networks:
      fastapi-htmx-todo-net:
    depends_on:
      - fastapi-htmx-todo
  fastapi-htmx-todo:
    env_file:
      - .env
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    ports:
      #- "${app_port}:8000"
      - "8000:8000"

    networks:
      fastapi-htmx-todo-net:


networks:
  fastapi-htmx-todo-net:


